<?php
namespace App\Helper;
class NewsHelper{
    public static function getNews(){
        return [
            [
                'category_id' => 1,
                'date' => '10/09/2023',
                'title' => 'Why reserves are decreasing, what needs to be done - what economists say',
                'type' => 1,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, \'Siyam Rupali\', Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country\'s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p>\r\n<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, \'Siyam Rupali\', Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM',
                'writer_id'=> 1,
                'image' => 'public/images/news/n1.jpg',
                'status' => 1,
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'category_id' => 4,
                'date' => '09/25/2023',
                'title' => 'The country\'s net reserves are now below 18 billion dollars: Zahid Hossain',
                'type' => 2,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM',
                'writer_id'=> 1,
                'image' => 'public/images/news/n2.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 3,
                'date' => '09/25/2023',
                'title' => "I'm not worried as I haven’t committed any crime: Dr Yunus",
                'type' => 3,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n3.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 2,
                'date' => '09/25/2023',
                'title' => 'Bangladeshi academics abroad condemn harassment of rights activists',
                'type' => 4,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n4.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 1,
                'date' => '09/25/2023',
                'title' => 'Rooppur plant is a symbol of strong bilateral ties: Putin',
                'type' => 1,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n5.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 2,
                'date' => '09/25/2023',
                'title' => 'Norwegian playwright Jon Fosse wins Nobel literature prize',
                'type' => 2,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n6.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 3,
                'date' => '09/25/2023',
                'title' => '34 eminent citizens concerned over harassment of Dr Yunus',
                'type' => 3,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n7.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 4,
                'date' => '09/25/2023',
                'title' => 'BB raises policy interest rate to 7.25pc to tame inflation',
                'type' => 4,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n8.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 5,
                'date' => '09/25/2023',
                'title' => 'Bangladesh Bank hikes interest rate on deposit, loan of financial institutions',
                'type' => 1,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n9.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 6,
                'date' => '09/25/2023',
                'title' => 'World Bank lowers GDP growth forecast for Bangladesh to 5.6pc',
                'type' => 2,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n10.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 7,
                'date' => '09/25/2023',
                'title' => 'Remittance plunges to 41-month low in September',
                'type' => 3,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n11.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 8,
                'date' => '09/25/2023',
                'title' => 'Green chilli price goes up again',
                'type' => 4,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n12.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 9,
                'date' => '09/25/2023',
                'title' => 'New Zealand field against England as ODI World Cup gets under way',
                'type' => 4,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n13.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 10,
                'date' => '09/25/2023',
                'title' => 'The World Cup to resurrect ODI cricket? Let’s hope so',
                'type' => 2,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n14.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 10,
                'date' => '09/25/2023',
                'title' => 'Kohli stardom supreme as stage set for World Cup opener',
                'type' => 3,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n15.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 11,
                'date' => '09/25/2023',
                'title' => 'Quader lies about ‘clandestine’ understating with US: Fakhrul',
                'type' => 4,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n16.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 9,
                'date' => '09/25/2023',
                'title' => 'New Zealand field against England as ODI World Cup gets under way',
                'type' => 4,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n13.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 10,
                'date' => '09/25/2023',
                'title' => 'The World Cup to resurrect ODI cricket? Let’s hope so',
                'type' => 2,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n14.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 10,
                'date' => '09/25/2023',
                'title' => 'Kohli stardom supreme as stage set for World Cup opener',
                'type' => 3,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n15.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
            [
                'category_id' => 11,
                'date' => '09/25/2023',
                'title' => 'Quader lies about ‘clandestine’ understating with US: Fakhrul',
                'type' => 4,
                'description' => '<p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">Every month the foreign currency reserves are decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">According to International Monetary Fund (IMF) BPM 6, reserves currently stand at $2,900 million (20.90 billion). </span><span style="box-sizing: border-box; vertical-align: inherit;">However, in the account that Bangladesh Bank gives to the IMF without disclosing to the public, the country`s real reserves are now about 1,700 crores or 17 billion dollars.</span></span></p><p style="box-sizing: border-box; font-family: Shurjo, SolaimanLipi, `Siyam Rupali`, Roboto, Arial, Helvetica, monospace; padding: 0px; font-size: var(--fs-18); line-height: 1.7; white-space-collapse: break-spaces; color: #121212; margin: 0px 0px var(--space1_6) 0px;"><span style="box-sizing: border-box; vertical-align: inherit;"><span style="box-sizing: border-box; vertical-align: inherit;">According to economists, reserves have decreased by $1 billion per month in the last 24 months or two years. </span><span style="box-sizing: border-box; vertical-align: inherit;">Since 2022, the flow of remittance or expatriate income to the country is also decreasing. </span><span style="box-sizing: border-box; vertical-align: inherit;">In the first three quarters of 2023, in the first three quarters of 2023, an average of 150 to 160 million dollars of expatriate income came to the country, while it was $ 200 million per month in 2022.</span></span></p>',
                'sort_description'=>'Every month the foreign currency reserves are decreasing. According to International Monetary Fund (IMF) BPM ',
                'writer_id'=> 1,
                'image' => 'public/images/news/n16.jpeg',
                'status' => 1,
                'created_by' => 1,
            ],
        ];
    }
}
